### ISSUE TITLE
4.1 compatibility?

### ISSUE THREAD

**Issue by arkenoi** [raffaeleflorio/qubes-url-redirector#43]
Apparently it does not work in 4.1 anymore: a disposable Qube starts, but nothing happens.

**Comment by raffaeleflorio** [comment]
Hi,
Unfortunately I don't have Qubes at hand. So I'm unable to try it with 4.1.
However this line: https://github.com/raffaeleflorio/qubes-url-redirector/blob/3b89f3def40124ce312eef615a872f1b496022dd/common/qvm-open-in-vm-we.py#L21 opens the URL in the VM. It's simply: qvm-open-in-vm <vmname> <url>.

Probably is this an issue about a VM config or about the OpenURL policy?

Raffaele Florio

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by arkenoi** [comment]
Veery strange thing. 

qvm-open-in-dvm works fine from the command line. "Open in disposable qube" starts new dvm and does nothing.
qvm-open-in-vm from the command line ignores the target VM and opens the dialog which VM I would like to use. "Open in default qube" pops up the same dialog, but does not open anything.

**Comment by raffaeleflorio** [comment]
IIRC this is a configurable policy. Do you have the same behavior of #37 ?

**Comment by ddevz** [comment]
> Hi, Unfortunately I don't have Qubes at hand. So I'm unable to try it with 4.1. However this line: https://github.com/raffaeleflorio/qubes-url-redirector/blob/3b89f3def40124ce312eef615a872f1b496022dd/common/qvm-open-in-vm-we.py#L21 opens the URL in the VM. It's simply: qvm-open-in-vm <vmname> <url>. Probably is this an issue about a VM config or about the OpenURL policy?

I thought I was able to fix this on one of my VMs by changing qvm-open-in-vm-we.py, in this general area:
os.execvp("qvm-open-in-vm", ["qvm-open-in-vm", msg["vmname"], msg["url"]]);

Unfortunately my system has reset since then and /opt changed back to the template version, so those changes are lost.

Trying to recreate it now, I'm finding the problem is not what I thought (I thought the problem was that when '$dispvm' that qvm-open-in-dvm needed to be called), so I have no idea what I magically did.  (i did add print to file output to /tmp)

of interest, creating a new program like this:
```
#!/usr/bin/env python3
import os

os.execvp("qvm-open-in-vm", ["qvm-open-in-vm", "$dispvm", "https://google.com"]);
```

and calling it from bash as user works fine, as does calling from bash after "sudo su" and after "sudo su -"

however, replacing qvm-open-in-vm-we.py with it still does not work.

**The symptom:**

Selecting "open in disposable qube" actually launches the new disposable qube, but what doesn't work is that the browser never comes up, the qube just hangs there forever.  The strange thing is that qvm-open-in-vm obviously gets called (so it's not a path problem), and the parameters are static, and it's not a python issue.  The only difference is that it's getting called from firefox instead of from bash.  but I don't know how that would effect it if its actually launching the disposable qube each time.


I had hoped to find logs of qvm-open-in-vm calls somewhere, but I never seemed to find them.

**Comment by unman** [comment]
I overwrote msg["vmname"] to have a constant target.
Examining journalctl in that target showed success when called directly, and failure when called from firefox.
The failed calls logged "qrexec-agent: Cannot access user instance remotely"

Changing the call in qvm-open-in-vm-we.py to use 'sudo -u user' restored functionality from firefox.
